// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfE5T9Zi_mrRPjUmp3pponnQMmBECodco',
    appId: '1:610317934612:web:424d2f8b772a494fe94701',
    messagingSenderId: '610317934612',
    projectId: 'academapp',
    authDomain: 'academapp.firebaseapp.com',
    storageBucket: 'academapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_w1akN4O6IKo6j8oleK8QACu04_lC6Z0',
    appId: '1:610317934612:android:73c43774e3fa229ce94701',
    messagingSenderId: '610317934612',
    projectId: 'academapp',
    storageBucket: 'academapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxzKsMtiZLEEu_wl_ULKoBc5XA_Z4oErE',
    appId: '1:610317934612:ios:02fe15a0b40f327ae94701',
    messagingSenderId: '610317934612',
    projectId: 'academapp',
    storageBucket: 'academapp.firebasestorage.app',
    iosBundleId: 'com.example.academyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxzKsMtiZLEEu_wl_ULKoBc5XA_Z4oErE',
    appId: '1:610317934612:ios:02fe15a0b40f327ae94701',
    messagingSenderId: '610317934612',
    projectId: 'academapp',
    storageBucket: 'academapp.firebasestorage.app',
    iosBundleId: 'com.example.academyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfE5T9Zi_mrRPjUmp3pponnQMmBECodco',
    appId: '1:610317934612:web:d66e9b6ece4b405ee94701',
    messagingSenderId: '610317934612',
    projectId: 'academapp',
    authDomain: 'academapp.firebaseapp.com',
    storageBucket: 'academapp.firebasestorage.app',
  );
}
